name: Test and Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    runs-on: alpine
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/go-setup@master
      - uses: actions/toolkit/go-test@master
  container:
    runs-on: alpine
    needs: [test]
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/docker-login@master
        with:
          audience: u:1:e73b80f5-854e-42da-a7c4-efdc22b5b2de
          ghcr: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push image
        uses: actions/toolkit/docker-push@master
        with:
          ghcr: true
  release:
    if: github.ref_type == 'tag'
    runs-on: alpine
    needs:
      - test
      - container
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/docker-login@master
        with:
          audience: u:1:e73b80f5-854e-42da-a7c4-efdc22b5b2de
          ghcr: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push image
        uses: actions/toolkit/docker-push@master
        with:
          ghcr: true
